# Site settings
title: ""
description: ""
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# URL settings
url: "https://mendezcolmenares.github.io"
baseurl: ""

# Markdown settings
markdown: kramdown

# Permalink settings (Optional)
permalink: pretty

# Other possible settings
show_downloads: false
