# Site settings
title: "mendezcolmenares.github.io"
description: "A minimal Jekyll theme for your GitHub Pages site."
theme: jekyll-theme-minimal

# URL settings
url: "https://mendezcolmenares.github.io"
baseurl: ""

# Markdown settings
markdown: kramdown

# Permalink settings (Optional)
permalink: pretty
